// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['notifications']['Handler']['SetContext'](arg1);
}

export function ShowNotification(arg1, arg2, arg3) {
  return window['go']['notifications']['Handler']['ShowNotification'](arg1, arg2, arg3);
}

export function StartListening() {
  return window['go']['notifications']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['notifications']['Handler']['StopListening']();
}
