// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate() {
  return window['go']['auth']['Handler']['Authenticate']();
}

export function ForgetPassword(arg1, arg2) {
  return window['go']['auth']['Handler']['ForgetPassword'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['auth']['Handler']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['auth']['Handler']['Logout']();
}

export function Register(arg1) {
  return window['go']['auth']['Handler']['Register'](arg1);
}

export function SendForgetPassword(arg1) {
  return window['go']['auth']['Handler']['SendForgetPassword'](arg1);
}

export function SendVerifyEmail(arg1) {
  return window['go']['auth']['Handler']['SendVerifyEmail'](arg1);
}

export function SetContext(arg1) {
  return window['go']['auth']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['auth']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['auth']['Handler']['StopListening']();
}
