// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domains} from '../models';
import {context} from '../models';

export function Authenticate():Promise<void>;

export function ChangePassword(arg1:domains.ChangePasswordDTO):Promise<void>;

export function ForgetPassword(arg1:string,arg2:domains.ForgetPasswordDTO):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function Register(arg1:domains.RegisterDTO):Promise<void>;

export function SendForgetPassword(arg1:string):Promise<void>;

export function SendVerifyEmail(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartListening():Promise<void>;

export function StopListening():Promise<void>;
