// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForgetPassword(arg1, arg2) {
  return window['go']['forget_password']['Handler']['ForgetPassword'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['forget_password']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['forget_password']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['forget_password']['Handler']['StopListening']();
}
