// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAvatar() {
  return window['go']['users']['Handler']['DeleteAvatar']();
}

export function GetCurrentUser() {
  return window['go']['users']['Handler']['GetCurrentUser']();
}

export function SearchUsers(arg1, arg2) {
  return window['go']['users']['Handler']['SearchUsers'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['users']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['users']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['users']['Handler']['StopListening']();
}

export function UpdateAvatar(arg1) {
  return window['go']['users']['Handler']['UpdateAvatar'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['users']['Handler']['UpdateUser'](arg1);
}
