// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domains} from '../models';
import {context} from '../models';

export function GetCurrentUser():Promise<domains.User>;

export function SearchUsers(arg1:domains.UsersFilters,arg2:domains.Pagination):Promise<Array<domains.User>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartListening():Promise<void>;

export function StopListening():Promise<void>;

export function UpdateAvatar(arg1:Array<number>):Promise<string>;

export function DeleteAvatar():Promise<void>;

export function UpdateUser(arg1:domains.UpdateUserDTO):Promise<domains.User>;
