// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessageReaction(arg1, arg2) {
  return window['go']['messages']['Handler']['AddMessageReaction'](arg1, arg2);
}

export function DeleteMessage(arg1, arg2) {
  return window['go']['messages']['Handler']['DeleteMessage'](arg1, arg2);
}

export function GetChatMessages(arg1, arg2) {
  return window['go']['messages']['Handler']['GetChatMessages'](arg1, arg2);
}

export function GetMessageByID(arg1) {
  return window['go']['messages']['Handler']['GetMessageByID'](arg1);
}

export function ListReactions() {
  return window['go']['messages']['Handler']['ListReactions']();
}

export function RemoveMessageReaction(arg1, arg2) {
  return window['go']['messages']['Handler']['RemoveMessageReaction'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['messages']['Handler']['SendMessage'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['messages']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['messages']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['messages']['Handler']['StopListening']();
}

export function UpdateMessage(arg1, arg2) {
  return window['go']['messages']['Handler']['UpdateMessage'](arg1, arg2);
}
