// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domains} from '../models';
import {context} from '../models';

export function AddMessageReaction(arg1:number,arg2:number):Promise<void>;

export function DeleteMessage(arg1:number,arg2:boolean):Promise<void>;

export function GetChatMessages(arg1:number,arg2:domains.Pagination):Promise<Array<domains.Message>>;

export function GetMessageByID(arg1:number):Promise<domains.Message>;

export function ListReactions():Promise<Array<domains.Reaction>>;

export function RemoveMessageReaction(arg1:number,arg2:number):Promise<void>;

export function SendMessage(arg1:number,arg2:string,arg3:any):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartListening():Promise<void>;

export function StopListening():Promise<void>;

export function UpdateMessage(arg1:number,arg2:string):Promise<void>;
