// Code generated by MockGen. DO NOT EDIT.
// Source: window.go
//
// Generated by this command:
//
//	mockgen -source=window.go -destination=../../mocks/window/window.go -package=mockwindow -exclude_interfaces=
//

// Package mockwindow is a generated GoMock package.
package mockwindow

import (
	reflect "reflect"

	fyne "fyne.io/fyne/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockWindow is a mock of Window interface.
type MockWindow struct {
	ctrl     *gomock.Controller
	recorder *MockWindowMockRecorder
	isgomock struct{}
}

// MockWindowMockRecorder is the mock recorder for MockWindow.
type MockWindowMockRecorder struct {
	mock *MockWindow
}

// NewMockWindow creates a new mock instance.
func NewMockWindow(ctrl *gomock.Controller) *MockWindow {
	mock := &MockWindow{ctrl: ctrl}
	mock.recorder = &MockWindowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindow) EXPECT() *MockWindowMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockWindow) Build(content fyne.CanvasObject) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Build", content)
}

// Build indicates an expected call of Build.
func (mr *MockWindowMockRecorder) Build(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockWindow)(nil).Build), content)
}

// Close mocks base method.
func (m *MockWindow) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockWindowMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWindow)(nil).Close))
}

// Show mocks base method.
func (m *MockWindow) Show() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Show")
}

// Show indicates an expected call of Show.
func (mr *MockWindowMockRecorder) Show() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockWindow)(nil).Show))
}
