// Code generated by MockGen. DO NOT EDIT.
// Source: errors.go
//
// Generated by this command:
//
//	mockgen -source=errors.go -destination=../../mocks/errors/mapper.go -package=mockerrors -exclude_interfaces=
//

// Package mockerrors is a generated GoMock package.
package mockerrors

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockErrorsMapper is a mock of ErrorsMapper interface.
type MockErrorsMapper struct {
	ctrl     *gomock.Controller
	recorder *MockErrorsMapperMockRecorder
	isgomock struct{}
}

// MockErrorsMapperMockRecorder is the mock recorder for MockErrorsMapper.
type MockErrorsMapperMockRecorder struct {
	mock *MockErrorsMapper
}

// NewMockErrorsMapper creates a new mock instance.
func NewMockErrorsMapper(ctrl *gomock.Controller) *MockErrorsMapper {
	mock := &MockErrorsMapper{ctrl: ctrl}
	mock.recorder = &MockErrorsMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorsMapper) EXPECT() *MockErrorsMapperMockRecorder {
	return m.recorder
}

// Map mocks base method.
func (m *MockErrorsMapper) Map(err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Map", err)
	ret0, _ := ret[0].(error)
	return ret0
}

// Map indicates an expected call of Map.
func (mr *MockErrorsMapperMockRecorder) Map(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Map", reflect.TypeOf((*MockErrorsMapper)(nil).Map), err)
}
