// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChat(arg1) {
  return window['go']['chats']['Handler']['CreateChat'](arg1);
}

export function GetUserChats(arg1) {
  return window['go']['chats']['Handler']['GetUserChats'](arg1);
}

export function SetContext(arg1) {
  return window['go']['chats']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['chats']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['chats']['Handler']['StopListening']();
}
