// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1) {
  return window['go']['profile']['Handler']['ChangePassword'](arg1);
}

export function SetContext(arg1) {
  return window['go']['profile']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['profile']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['profile']['Handler']['StopListening']();
}
