// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/chats_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,TokensRepository,UsersRepository,WebSocketsRepository,SettingsRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfcGUI/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockChatsRepository is a mock of ChatsRepository interface.
type MockChatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatsRepositoryMockRecorder
	isgomock struct{}
}

// MockChatsRepositoryMockRecorder is the mock recorder for MockChatsRepository.
type MockChatsRepositoryMockRecorder struct {
	mock *MockChatsRepository
}

// NewMockChatsRepository creates a new mock instance.
func NewMockChatsRepository(ctrl *gomock.Controller) *MockChatsRepository {
	mock := &MockChatsRepository{ctrl: ctrl}
	mock.recorder = &MockChatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsRepository) EXPECT() *MockChatsRepositoryMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockChatsRepository) CreateChat(ctx context.Context, accessToken string, chat domains.Chat) (*domains.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, accessToken, chat)
	ret0, _ := ret[0].(*domains.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatsRepositoryMockRecorder) CreateChat(ctx, accessToken, chat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatsRepository)(nil).CreateChat), ctx, accessToken, chat)
}

// GetChatMessages mocks base method.
func (m *MockChatsRepository) GetChatMessages(ctx context.Context, accessToken string, chatID uint64, pagination *domains.Pagination) ([]domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMessages", ctx, accessToken, chatID, pagination)
	ret0, _ := ret[0].([]domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMessages indicates an expected call of GetChatMessages.
func (mr *MockChatsRepositoryMockRecorder) GetChatMessages(ctx, accessToken, chatID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMessages", reflect.TypeOf((*MockChatsRepository)(nil).GetChatMessages), ctx, accessToken, chatID, pagination)
}

// GetUserChats mocks base method.
func (m *MockChatsRepository) GetUserChats(ctx context.Context, accessToken string, pagination *domains.Pagination) ([]domains.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserChats", ctx, accessToken, pagination)
	ret0, _ := ret[0].([]domains.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserChats indicates an expected call of GetUserChats.
func (mr *MockChatsRepositoryMockRecorder) GetUserChats(ctx, accessToken, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserChats", reflect.TypeOf((*MockChatsRepository)(nil).GetUserChats), ctx, accessToken, pagination)
}
