// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/messages_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,TokensRepository,UsersRepository,ChatsRepository,WebSocketsRepository,SettingsRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfcGUI/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagesRepository is a mock of MessagesRepository interface.
type MockMessagesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesRepositoryMockRecorder
	isgomock struct{}
}

// MockMessagesRepositoryMockRecorder is the mock recorder for MockMessagesRepository.
type MockMessagesRepositoryMockRecorder struct {
	mock *MockMessagesRepository
}

// NewMockMessagesRepository creates a new mock instance.
func NewMockMessagesRepository(ctrl *gomock.Controller) *MockMessagesRepository {
	mock := &MockMessagesRepository{ctrl: ctrl}
	mock.recorder = &MockMessagesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagesRepository) EXPECT() *MockMessagesRepositoryMockRecorder {
	return m.recorder
}

// AddMessageReaction mocks base method.
func (m *MockMessagesRepository) AddMessageReaction(ctx context.Context, accessToken string, dto domains.MessageReactionDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessageReaction", ctx, accessToken, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessageReaction indicates an expected call of AddMessageReaction.
func (mr *MockMessagesRepositoryMockRecorder) AddMessageReaction(ctx, accessToken, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageReaction", reflect.TypeOf((*MockMessagesRepository)(nil).AddMessageReaction), ctx, accessToken, dto)
}

// DeleteMessage mocks base method.
func (m *MockMessagesRepository) DeleteMessage(ctx context.Context, accessToken string, dto domains.DeleteMessageDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, accessToken, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessagesRepositoryMockRecorder) DeleteMessage(ctx, accessToken, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessagesRepository)(nil).DeleteMessage), ctx, accessToken, dto)
}

// GetChatMessages mocks base method.
func (m *MockMessagesRepository) GetChatMessages(ctx context.Context, accessToken string, chatID uint64, pagination *domains.Pagination) ([]domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMessages", ctx, accessToken, chatID, pagination)
	ret0, _ := ret[0].([]domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMessages indicates an expected call of GetChatMessages.
func (mr *MockMessagesRepositoryMockRecorder) GetChatMessages(ctx, accessToken, chatID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMessages", reflect.TypeOf((*MockMessagesRepository)(nil).GetChatMessages), ctx, accessToken, chatID, pagination)
}

// GetMessageByID mocks base method.
func (m *MockMessagesRepository) GetMessageByID(ctx context.Context, accessToken string, messageID uint64) (*domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, accessToken, messageID)
	ret0, _ := ret[0].(*domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessagesRepositoryMockRecorder) GetMessageByID(ctx, accessToken, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessagesRepository)(nil).GetMessageByID), ctx, accessToken, messageID)
}

// ListReactions mocks base method.
func (m *MockMessagesRepository) ListReactions(ctx context.Context, accessToken string) ([]domains.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReactions", ctx, accessToken)
	ret0, _ := ret[0].([]domains.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReactions indicates an expected call of ListReactions.
func (mr *MockMessagesRepositoryMockRecorder) ListReactions(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReactions", reflect.TypeOf((*MockMessagesRepository)(nil).ListReactions), ctx, accessToken)
}

// RemoveMessageReaction mocks base method.
func (m *MockMessagesRepository) RemoveMessageReaction(ctx context.Context, accessToken string, dto domains.MessageReactionDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMessageReaction", ctx, accessToken, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMessageReaction indicates an expected call of RemoveMessageReaction.
func (mr *MockMessagesRepositoryMockRecorder) RemoveMessageReaction(ctx, accessToken, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMessageReaction", reflect.TypeOf((*MockMessagesRepository)(nil).RemoveMessageReaction), ctx, accessToken, dto)
}

// UpdateMessage mocks base method.
func (m *MockMessagesRepository) UpdateMessage(ctx context.Context, accessToken string, dto domains.UpdateMessageDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessage", ctx, accessToken, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessage indicates an expected call of UpdateMessage.
func (mr *MockMessagesRepositoryMockRecorder) UpdateMessage(ctx, accessToken, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessage", reflect.TypeOf((*MockMessagesRepository)(nil).UpdateMessage), ctx, accessToken, dto)
}
