// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/reactions_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,TokensRepository,UsersRepository,ChatsRepository,MessagesRepository,WebSocketsRepository,SettingsRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfcGUI/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockReactionsRepository is a mock of ReactionsRepository interface.
type MockReactionsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReactionsRepositoryMockRecorder
	isgomock struct{}
}

// MockReactionsRepositoryMockRecorder is the mock recorder for MockReactionsRepository.
type MockReactionsRepositoryMockRecorder struct {
	mock *MockReactionsRepository
}

// NewMockReactionsRepository creates a new mock instance.
func NewMockReactionsRepository(ctrl *gomock.Controller) *MockReactionsRepository {
	mock := &MockReactionsRepository{ctrl: ctrl}
	mock.recorder = &MockReactionsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReactionsRepository) EXPECT() *MockReactionsRepositoryMockRecorder {
	return m.recorder
}

// AddMessageReaction mocks base method.
func (m *MockReactionsRepository) AddMessageReaction(ctx context.Context, accessToken string, dto domains.MessageReactionDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessageReaction", ctx, accessToken, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessageReaction indicates an expected call of AddMessageReaction.
func (mr *MockReactionsRepositoryMockRecorder) AddMessageReaction(ctx, accessToken, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageReaction", reflect.TypeOf((*MockReactionsRepository)(nil).AddMessageReaction), ctx, accessToken, dto)
}

// ListReactions mocks base method.
func (m *MockReactionsRepository) ListReactions(ctx context.Context) ([]domains.Reaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReactions", ctx)
	ret0, _ := ret[0].([]domains.Reaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReactions indicates an expected call of ListReactions.
func (mr *MockReactionsRepositoryMockRecorder) ListReactions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReactions", reflect.TypeOf((*MockReactionsRepository)(nil).ListReactions), ctx)
}

// RemoveMessageReaction mocks base method.
func (m *MockReactionsRepository) RemoveMessageReaction(ctx context.Context, accessToken string, dto domains.MessageReactionDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMessageReaction", ctx, accessToken, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMessageReaction indicates an expected call of RemoveMessageReaction.
func (mr *MockReactionsRepositoryMockRecorder) RemoveMessageReaction(ctx, accessToken, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMessageReaction", reflect.TypeOf((*MockReactionsRepository)(nil).RemoveMessageReaction), ctx, accessToken, dto)
}
