// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/tokens_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,UsersRepository,MessagesRepository,ChatsRepository,WebSocketsRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfcGUI/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockTokensRepository is a mock of TokensRepository interface.
type MockTokensRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokensRepositoryMockRecorder
	isgomock struct{}
}

// MockTokensRepositoryMockRecorder is the mock recorder for MockTokensRepository.
type MockTokensRepositoryMockRecorder struct {
	mock *MockTokensRepository
}

// NewMockTokensRepository creates a new mock instance.
func NewMockTokensRepository(ctrl *gomock.Controller) *MockTokensRepository {
	mock := &MockTokensRepository{ctrl: ctrl}
	mock.recorder = &MockTokensRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokensRepository) EXPECT() *MockTokensRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockTokensRepository) Load(ctx context.Context) (*domains.TokensDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx)
	ret0, _ := ret[0].(*domains.TokensDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockTokensRepositoryMockRecorder) Load(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockTokensRepository)(nil).Load), ctx)
}

// Save mocks base method.
func (m *MockTokensRepository) Save(ctx context.Context, tokens *domains.TokensDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTokensRepositoryMockRecorder) Save(ctx, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTokensRepository)(nil).Save), ctx, tokens)
}
