// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=../../mocks/repositories/websockets_repository.go -package=mockrepositories -exclude_interfaces=AuthRepository,TokensRepository,UsersRepository,ChatsRepository,SettingsRepository
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	domains "github.com/DKhorkov/kfcGUI/internal/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockWebSocketsRepository is a mock of WebSocketsRepository interface.
type MockWebSocketsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebSocketsRepositoryMockRecorder
	isgomock struct{}
}

// MockWebSocketsRepositoryMockRecorder is the mock recorder for MockWebSocketsRepository.
type MockWebSocketsRepositoryMockRecorder struct {
	mock *MockWebSocketsRepository
}

// NewMockWebSocketsRepository creates a new mock instance.
func NewMockWebSocketsRepository(ctrl *gomock.Controller) *MockWebSocketsRepository {
	mock := &MockWebSocketsRepository{ctrl: ctrl}
	mock.recorder = &MockWebSocketsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebSocketsRepository) EXPECT() *MockWebSocketsRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWebSocketsRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWebSocketsRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWebSocketsRepository)(nil).Close))
}

// Connect mocks base method.
func (m *MockWebSocketsRepository) Connect(ctx context.Context, accessToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockWebSocketsRepositoryMockRecorder) Connect(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockWebSocketsRepository)(nil).Connect), ctx, accessToken)
}

// ReadMessage mocks base method.
func (m *MockWebSocketsRepository) ReadMessage(ctx context.Context) (*domains.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMessage", ctx)
	ret0, _ := ret[0].(*domains.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMessage indicates an expected call of ReadMessage.
func (mr *MockWebSocketsRepositoryMockRecorder) ReadMessage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMessage", reflect.TypeOf((*MockWebSocketsRepository)(nil).ReadMessage), ctx)
}

// WriteMessage mocks base method.
func (m *MockWebSocketsRepository) WriteMessage(ctx context.Context, message domains.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessage indicates an expected call of WriteMessage.
func (mr *MockWebSocketsRepositoryMockRecorder) WriteMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessage", reflect.TypeOf((*MockWebSocketsRepository)(nil).WriteMessage), ctx, message)
}
