// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=../../mocks/handler/handler.go -package=mockhandler -exclude_interfaces=
//

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// SetContext mocks base method.
func (m *MockHandler) SetContext(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContext", ctx)
}

// SetContext indicates an expected call of SetContext.
func (mr *MockHandlerMockRecorder) SetContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockHandler)(nil).SetContext), ctx)
}

// StartListening mocks base method.
func (m *MockHandler) StartListening() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartListening")
}

// StartListening indicates an expected call of StartListening.
func (mr *MockHandlerMockRecorder) StartListening() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartListening", reflect.TypeOf((*MockHandler)(nil).StartListening))
}

// StopListening mocks base method.
func (m *MockHandler) StopListening() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopListening")
}

// StopListening indicates an expected call of StopListening.
func (mr *MockHandlerMockRecorder) StopListening() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopListening", reflect.TypeOf((*MockHandler)(nil).StopListening))
}
