// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function SetContext(arg1:context.Context):Promise<void>;

export function ShowNotification(arg1:string,arg2:string,arg3:number):Promise<void>;

export function StartListening():Promise<void>;

export function StopListening():Promise<void>;
