// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['notification']['Handler']['SetContext'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['notification']['Handler']['ShowNotification'](arg1, arg2);
}

export function StartListening() {
  return window['go']['notification']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['notification']['Handler']['StopListening']();
}
