// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatMessages(arg1, arg2) {
  return window['go']['chat']['Handler']['GetChatMessages'](arg1, arg2);
}

export function GetCurrentUser() {
  return window['go']['chat']['Handler']['GetCurrentUser']();
}

export function GetUserChats(arg1) {
  return window['go']['chat']['Handler']['GetUserChats'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['chat']['Handler']['SendMessage'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['chat']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['chat']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['chat']['Handler']['StopListening']();
}

export function ToggleTheme() {
  return window['go']['chat']['Handler']['ToggleTheme']();
}
