// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domains} from '../models';
import {context} from '../models';

export function GetChatMessages(arg1:number,arg2:domains.Pagination):Promise<Array<domains.Message>>;

export function GetCurrentUser():Promise<domains.User>;

export function GetUserChats(arg1:domains.Pagination):Promise<Array<domains.Chat>>;

export function SendMessage(arg1:number,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartListening():Promise<void>;

export function StopListening():Promise<void>;

export function ToggleTheme():Promise<domains.ThemeType>;
