version: '3'

tasks:
  clean_up:
    desc: "Clean up all folders and files."
    dir: ../
    aliases:
      - clean
    cmds:
      #      - sudo rm -rf logs/
      - sudo rm -rf coverage/
      - sudo rm -rf tokens.json
      - sudo rm -rf bin/

  tests:
    desc: "Run tests and save coverage to coverage folder."
    aliases:
      - test
    dir: ../
    cmds:
      - task: create_postgres_folders
      - sudo chmod -R 777 postgres_data
      - sudo chmod -R 777 postgres_backups
      - mkdir -p ./coverage
      - |
        printf "integration={{.integration}}\n\n"  # View flag value
        if [ "{{.integration}}" == "true" ]; then
          go test -v -shuffle=on -coverprofile ./coverage/coverage.out -coverpkg=$(go list ./... | grep -v -F -f .coverignore | paste -sd, -) ./... -tags=integration
        else
          go test -v -shuffle=on -coverprofile ./coverage/coverage.out -coverpkg=$(go list ./... | grep -v -F -f .coverignore | paste -sd, -) ./...
        fi
      - go tool cover -html ./coverage/coverage.out -o ./coverage/coverage.html
    vars:
      integration:
        sh: echo "${integration:-false}"  # false by default

  benchmarks:
    desc: "Run benchmarks."
    aliases:
      - bench
    dir: ../
    cmd: go test -v ./... -bench=. -run=xxx -benchmem >> bench.txt

  linters:
    desc: "Run linters."
    aliases:
      - lint
    dir: ../
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - export PATH=$PATH:$(go env GOPATH)/bin
      - golangci-lint run -v --fix

  docker_rules:
    desc: "Дает возможность использовать docker без sudo для fyne-cross"
    cmds:
      - sudo usermod -aG docker $USER
      - newgrp docker

  build:
    desc: "Сборка GUI-приложения под все платформы через fyne-cross"
    dir: ../
    vars:
      PACKAGE_PATH: ./cmd
      APP_NAME: kfc
      ICON_PATH: "./assets/icon.png"
      APP_ID: "com.dkhorkov.kfc"
      OUTPUT_DIR: ./bin
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}

      # 1. Установка инструмента (если еще нет)
      - go install github.com/fyne-io/fyne-cross@latest

      # --- LINUX ---
      - fyne-cross linux -arch amd64 -app-id {{.APP_ID}} -icon {{.ICON_PATH}} {{.PACKAGE_PATH}}
      - mv fyne-cross/bin/linux-amd64/cmd {{.OUTPUT_DIR}}/{{.APP_NAME}}_linux_amd64
      - fyne-cross linux -arch 386 -app-id {{.APP_ID}} -icon {{.ICON_PATH}} {{.PACKAGE_PATH}}
      - mv fyne-cross/bin/linux-386/cmd {{.OUTPUT_DIR}}/{{.APP_NAME}}_linux_386
      - fyne-cross linux -arch arm64 -app-id {{.APP_ID}} -icon {{.ICON_PATH}} {{.PACKAGE_PATH}}
      - mv fyne-cross/bin/linux-arm64/cmd {{.OUTPUT_DIR}}/{{.APP_NAME}}_linux_arm64

      # --- WINDOWS ---
      - fyne-cross windows -arch amd64 -app-id {{.APP_ID}} -name {{.APP_NAME}}_windows_amd64.exe -icon {{.ICON_PATH}} {{.PACKAGE_PATH}}
      - mv fyne-cross/bin/windows-amd64/{{.APP_NAME}}_windows_amd64.exe {{.OUTPUT_DIR}}/{{.APP_NAME}}_windows_amd64.exe
      - fyne-cross windows -arch 386 -app-id {{.APP_ID}} -name {{.APP_NAME}}_windows_386.exe -icon {{.ICON_PATH}} {{.PACKAGE_PATH}}
      - mv fyne-cross/bin/windows-386/{{.APP_NAME}}_windows_386.exe {{.OUTPUT_DIR}}/{{.APP_NAME}}_windows_386.exe

      # --- MACOS (Darwin) --- sdk  https://github.com/phracker/macosx-sdks/releases
      - fyne-cross darwin -arch amd64 -app-id {{.APP_ID}} -macosx-sdk-path ./sdk/MacOSX11.3.sdk -icon {{.ICON_PATH}} {{.PACKAGE_PATH}}
      - mv fyne-cross/bin/darwin-amd64/cmd {{.OUTPUT_DIR}}/{{.APP_NAME}}_darwin_amd64
      - fyne-cross darwin -arch arm64 -app-id {{.APP_ID}} -macosx-sdk-path ./sdk/MacOSX11.3.sdk -icon {{.ICON_PATH}} {{.PACKAGE_PATH}}
      - mv fyne-cross/bin/darwin-arm64/cmd {{.OUTPUT_DIR}}/{{.APP_NAME}}_darwin_arm64

      - rm -rf ./fyne-cross

      - echo "Все сборки готовы и находятся в папке {{.OUTPUT_DIR}}"
