// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domains} from '../models';
import {context} from '../models';

export function GetSettings():Promise<domains.Settings>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartListening():Promise<void>;

export function StopListening():Promise<void>;

export function UpdateSettings(arg1:domains.Settings):Promise<domains.Settings>;
