// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTheme() {
  return window['go']['settings']['Handler']['GetTheme']();
}

export function SetContext(arg1) {
  return window['go']['settings']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['settings']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['settings']['Handler']['StopListening']();
}

export function ToggleTheme() {
  return window['go']['settings']['Handler']['ToggleTheme']();
}
