// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['settings']['Handler']['GetSettings']();
}

export function SetContext(arg1) {
  return window['go']['settings']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['settings']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['settings']['Handler']['StopListening']();
}

export function UpdateSettings(arg1) {
  return window['go']['settings']['Handler']['UpdateSettings'](arg1);
}
