// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchUsers(arg1, arg2) {
  return window['go']['search_users']['Handler']['SearchUsers'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['search_users']['Handler']['SetContext'](arg1);
}

export function StartListening() {
  return window['go']['search_users']['Handler']['StartListening']();
}

export function StopListening() {
  return window['go']['search_users']['Handler']['StopListening']();
}
