// Code generated by MockGen. DO NOT EDIT.
// Source: application.go
//
// Generated by this command:
//
//	mockgen -source=application.go -destination=../../mocks/application/application.go -package=mockapplication -exclude_interfaces=
//

// Package mockapplication is a generated GoMock package.
package mockapplication

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApplication is a mock of Application interface.
type MockApplication struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationMockRecorder
	isgomock struct{}
}

// MockApplicationMockRecorder is the mock recorder for MockApplication.
type MockApplicationMockRecorder struct {
	mock *MockApplication
}

// NewMockApplication creates a new mock instance.
func NewMockApplication(ctrl *gomock.Controller) *MockApplication {
	mock := &MockApplication{ctrl: ctrl}
	mock.recorder = &MockApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplication) EXPECT() *MockApplicationMockRecorder {
	return m.recorder
}

// BindHandlers mocks base method.
func (m *MockApplication) BindHandlers() []any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindHandlers")
	ret0, _ := ret[0].([]any)
	return ret0
}

// BindHandlers indicates an expected call of BindHandlers.
func (mr *MockApplicationMockRecorder) BindHandlers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindHandlers", reflect.TypeOf((*MockApplication)(nil).BindHandlers))
}

// Shutdown mocks base method.
func (m *MockApplication) Shutdown(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown", ctx)
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockApplicationMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockApplication)(nil).Shutdown), ctx)
}

// Startup mocks base method.
func (m *MockApplication) Startup(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Startup", ctx)
}

// Startup indicates an expected call of Startup.
func (mr *MockApplicationMockRecorder) Startup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Startup", reflect.TypeOf((*MockApplication)(nil).Startup), ctx)
}
