name: linters-workflow
run-name: ${{ github.actor }} is testing changes
on: [push, pull_request]
jobs:
  linters:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - name: Install system C-libraries
        run: |
         sudo apt-get update
         sudo apt-get install -y libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
      - name: Prepare dummy frontend dist
        run: |
          mkdir -p cmd/v2/frontend/dist
          touch cmd/v2/frontend/dist/placeholder.txt
      - name: Run Linters
        run: golangci-lint run -v --fix
